// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxtigKvjkxZTcFujFiXCkK7jtAjj0mLes',
    appId: '1:1077789577585:web:098e51aa54a1a7850726d0',
    messagingSenderId: '1077789577585',
    projectId: 'shopifie-tanyarajhans7',
    authDomain: 'shopifie-tanyarajhans7.firebaseapp.com',
    storageBucket: 'shopifie-tanyarajhans7.appspot.com',
    measurementId: 'G-35WYJHT9GR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKu2q9mqEMjefb7DD7moZ3Fd_8VCmYH7E',
    appId: '1:1077789577585:ios:05695773524deb4a0726d0',
    messagingSenderId: '1077789577585',
    projectId: 'shopifie-tanyarajhans7',
    storageBucket: 'shopifie-tanyarajhans7.appspot.com',
    iosClientId: '1077789577585-9ch3ahca369pc7nvi3rel5660cbshpkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopifie',
  );
}
